### ISSUE TITLE
Error while building this project

### ISSUE THREAD

**Issue by mathieu-chauvet** [balena-io-playground/balena-rpi-nodejs-basic-gpio#5]
I had the following error while building this project. 

I simply cloned it, added my resin git repo and pushed. 

```
[main]  npm
[main]
[main]  WARN
[main]  package.json basic-gpio@0.0.1 No repository field.
[main]
[main]  > basic-gpio@0.0.1 preinstall /usr/src/app
[main]  > bash deps.sh
[main]  npm http
[main]  GET https://registry.npmjs.org/pi-pins
[main]
[main]  npm
[main]
[main]  http
[main]
[main]  GET https://registry.npmjs.org/pi-pins
[main]
[Info]  Still working...
[main]  npm http GET https://registry.npmjs.org/pi-pins
[main]
[main]  npm ERR!
[main]   Error: CERT_UNTRUSTED
[main]
[main]  npm ERR!     at SecurePair.<anonymous> (tls.js:1362:32)
[main]  npm
[main]  ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
[main]
[main]  npm ERR!     at SecurePair.maybeInitFinished (tls.js:974:10)
[main]
[main]  npm ERR!     at CleartextStream.read [as _read] (tls.js:462:15)
[main]
[main]  npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
[main]  npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
[main]  npm ERR!     at doWrite (_stream_writable.js:221:10)
[main]  npm ERR!     at writeOrBuffer (_stream_writable.js:211:5)
[main]
[main]  npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
[main]
[main]  npm
[main]
[main]  ERR!
[main]       at write (_stream_readable.js:583:24)
[main]  npm
[main]   ERR!
[main]   If you need help, you may report this log at:
[main]  npm ERR!
[main]       <http://github.com/isaacs/npm/issues>
[main]  npm ERR!
[main]   or email it to:
[main]
[main]  npm ERR!     <npm-@googlegroups.com>
[main]
[main]
[main]  npm
[main]  ERR!
[main]  System Linux 4.12.13
[main]
[main]  npm ERR! command
[main]   "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--unsafe-perm"
[main]
[main]  npm
[main]   ERR!
[main]
[main]  cwd /usr/src/app
[main]  npm
[main]
[main]  ERR!
[main]   node -v v0.10.22
[main]
[main]  npm
[main]  ERR! npm -v 1.3.14
[main]
[main]  npm
[main]  ERR!
[main]
[main]  npm ERR!
[main]   Additional logging details can be found in:
[main]
[main]  npm ERR!
[main]       /usr/src/app/npm-debug.log
[main]
[main]  npm ERR! not ok code 0
[main]
[main]  Removing intermediate container 3b80f9710032
[main]  The command '/bin/sh -c DEBIAN_FRONTEND=noninteractive JOBS=MAX npm install --unsafe-perm' returned a non-zero code: 1
[Info]  Uploading images
[Success]  Successfully uploaded images
[Error]  Some services failed to build:
[Error]    Service: main
[Error]      Error: The command '/bin/sh -c DEBIAN_FRONTEND=noninteractive JOBS=MAX npm install --unsafe-perm' returned a non-zero code: 1
[Error]  Not deploying release.
```

**Comment by Stephan-e** [comment]
I have the same issue when building this project

**Comment by mikeboehm** [comment]
This PR fixes it: https://github.com/balena-io-playground/balena-rpi-nodejs-basic-gpio/pull/6
